const $=id=>document.getElementById(id);const C=(n,k)=>{let r=1;for(let i=1;i<=k;i++)r=r*(n-k+i)/i;return Math.round(r)};
$('game').onchange=()=>{$('custom').classList.toggle('hidden',$('game').value!=='custom')};
function parseNums(line){return (line.match(/\d+/g)||[]).map(Number).filter(n=>n>0&&n<=100)}
function cfg(){if($('game').value==='ohota')return{fields:2,pick:4,max:20,name:'Охота'};if($('game').value==='zabava')return{fields:1,pick:12,max:24,name:'Забава'};return{fields:+$('fields').value,pick:+$('pick').value,max:+$('maxnum').value,name:'Свой формат'}}
function rowsFromText(t,conf){return t.split(/\r?\n/).map(parseNums).filter(a=>a.length>=conf.fields*conf.pick).map(a=>a.slice(-conf.fields*conf.pick));}
function demo(){let r=[];for(let i=0;i<375;i++){let row=[];for(let f=0;f<2;f++){let s=new Set();while(s.size<4)s.add(1+Math.floor(Math.random()*20));row.push(...[...s].sort((a,b)=>a-b))}r.push(row)}return r}
function pairs(arr){let out=[];for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++)out.push([arr[i],arr[j]].join('-'));return out}
function analyze(rows,conf){let perField=[];for(let f=0;f<conf.fields;f++){let freq=Object.fromEntries(Array.from({length:conf.max},(_,i)=>[i+1,0]));let pair={};for(const row of rows){let a=row.slice(f*conf.pick,(f+1)*conf.pick);a.forEach(n=>freq[n]=(freq[n]||0)+1);pairs(a).forEach(p=>pair[p]=(pair[p]||0)+1)}let nums=Object.entries(freq).map(([n,c])=>({n:+n,c})).sort((a,b)=>b.c-a.c);let pp=Object.entries(pair).sort((a,b)=>b[1]-a[1]).slice(0,20);let combos=[];let top=nums.slice(0,12).map(x=>x.n);function rec(start,cur){if(cur.length===conf.pick){let score=cur.reduce((s,n)=>s+(freq[n]||0),0)+pairs(cur).reduce((s,p)=>s+(pair[p]||0)*2,0);let sum=cur.reduce((a,b)=>a+b,0);let even=cur.filter(n=>n%2===0).length;score-=Math.abs(even-conf.pick/2)*3; combos.push({cur:[...cur],score,sum,even});return}for(let i=start;i<top.length;i++)rec(i+1,[...cur,top[i]])}rec(0,[]);combos.sort((a,b)=>b.score-a.score);perField.push({nums,pp,combos:combos.slice(0,10)})}return perField}
function render(rows,conf,res){let n=C(conf.max,conf.pick);let html=`<h2>${conf.name}</h2><p>Тиражей в файле: <b>${rows.length}</b>. Вероятность одной конкретной комбинации в поле: <b>1/${n}</b> ≈ <b>${(100/n).toFixed(4)}%</b>.</p><p class="warn">Это аналитический рейтинг по архиву, не гарантия выигрыша.</p>`;res.forEach((r,i)=>{html+=`<h3>Поле ${i+1}</h3><h4>Горячие числа</h4><p>${r.nums.slice(0,10).map(x=>`<span class="pill">${x.n}: ${x.c}</span>`).join('')}</p><h4>Сильные пары</h4><p>${r.pp.slice(0,8).map(x=>`<span class="pill">${x[0]}: ${x[1]}</span>`).join('')}</p><h4>Топ вариантов CSI</h4>`;r.combos.slice(0,5).forEach((c,k)=>html+=`<div class="combo">#${k+1}: <b>${c.cur.join(' • ')}</b><br>CSI: ${c.score.toFixed(1)}, сумма: ${c.sum}, четных: ${c.even}</div>`)});$('out').innerHTML=html;$('out').classList.remove('hidden')}
$('demo').onclick=()=>{let conf=cfg(); if(conf.name!=='Охота') conf={fields:2,pick:4,max:20,name:'Охота'}; let rows=demo(); render(rows,conf,analyze(rows,conf))};
$('analyze').onclick=async()=>{let conf=cfg();let f=$('file').files[0];if(!f){alert('Сначала выберите CSV или нажмите Демо');return}let text=await f.text();let rows=rowsFromText(text,conf);if(!rows.length){alert('Не удалось распознать числа в файле');return}render(rows,conf,analyze(rows,conf))};
